repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: loki
    namespace: grafana-stack
    chart: grafana/loki
    version: 6.24.0
    values:
      - ./values/loki.values.yaml
  - name: grafana
    namespace: grafana-stack
    chart: grafana/grafana
    version: 8.8.5
    values:
      - ./values/grafana.values.yaml
  - name: alloy
    namespace: grafana-stack
    chart: grafana/alloy
    version: 0.10.1
    values:
      - ./values/alloy.values.yaml
    set:
      - name: config.alloy
        file: ./values/config.alloy
  - name: tempo
    namespace: grafana-stack
    version: 1.16.0
    chart: grafana/tempo
    values:
      - ./values/tempo.values.yaml
  - name: pyroscope
    namespace: grafana-stack
    version: 1.11.0
    chart: grafana/pyroscope
    values:
      - ./values/pyroscope.values.yaml
  - name: prometheus
    namespace: grafana-stack
    version: 26.1.0
    chart: prometheus-community/prometheus
    values:
      - ./values/prometheus.values.yaml



      
