repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: loki
    namespace: grafana-stack
    chart: grafana/loki
    version: 6.27.0
    values:
      - ./values/loki.values.yaml
  - name: grafana
    namespace: grafana-stack
    chart: grafana/grafana
    version: 8.10.1
    values:
      - ./values/grafana.values.yaml
  - name: alloy
    namespace: grafana-stack
    chart: grafana/alloy
    version: 0.12.1
    values:
      - ./values/alloy.values.yaml
    set:
      - name: config.alloy
        file: ./values/config.alloy
  - name: tempo
    namespace: grafana-stack
    version: 1.18.2
    chart: grafana/tempo
    values:
      - ./values/tempo.values.yaml
  - name: pyroscope
    namespace: grafana-stack
    version: 1.13.4
    chart: grafana/pyroscope
    values:
      - ./values/pyroscope.values.yaml
  - name: prometheus
    namespace: grafana-stack
    version: 27.5.1
    chart: prometheus-community/prometheus
    values:
      - ./values/prometheus.values.yaml



      
