loki:
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    bucketNames:
      chunks: "chunks"
      ruler: "ruler"
      admin: "admin"
    type: s3
    s3:
      s3: null
      endpoint: "s3://minio.minio.svc.cluster.local"
      region: "us-east-1"
      secretAccessKey: "minio123"
      accessKeyId: "minio"
      signatureVersion: null
      s3ForcePathStyle: false
      insecure: true
      http_config: {}
      # -- Check https://grafana.com/docs/loki/latest/configure/#s3_storage_config for more info on how to provide a backoff_config
      backoff_config: {}
 

