---
storage:
  trace:
    backend: s3
    s3:
      access_key: 'minio'
      secret_key: 'minio123'
      bucket: 'tempo-traces'
      endpoint: 'minio.minio.svc.cluster.local'
      insecure: true
#MinIO storage configuration
minio:
  enabled: false
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false

