---
storage:
  trace:
    backend: local
    local:
      path: /var/tempo/traces
      wal:
        path: /var/tempo/wal
#MinIO storage configuration
minio:
  enabled: false
traces:
  otlp:
    grpc:
      enabled: true
    http:
      enabled: true
  zipkin:
    enabled: false
  jaeger:
    thriftHttp:
      enabled: false
  opencensus:
    enabled: false

ingress:
  enabled: true
  # For Kubernetes >= 1.18 you should specify the ingress-controller via the field ingressClassName
  # See https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress
  ingressClassName: nginx-internal
  # Values can be templated
  annotations: 
    kubernetes.io/ingress.class: nginx-internal
  path: /

  # pathType is only for k8s >= 1.1=
  pathType: Prefix

  hosts:
    - tempo.home
