
deploymentMode: SingleBinary<->SimpleScalable

loki:
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  auth_enabled: false
  schemaConfig:
    configs:
      - from: 2024-04-01
        store: tsdb
        object_store: filesystem
        schema: v13
        index:
          prefix: loki_index_
          period: 24h

  storage:
    type: filesystem
    filesystem:
      chunks_directory: /var/loki/chunks
      rules_directory: /var/loki/rules
      admin_api_directory: /var/loki/admin

singleBinary:
  replicas: 1
write: 
  replicas: 1
read: 
  replicas: 1
backend: 
  replicas: 1
