repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts

releases:
  - name: alloy
    namespace: grafana-stack
    chart: grafana/alloy
    version: 1.0.3
    values:
      - ./values/alloy.values.yaml
    set:
      - name: configMap.data."config.alloy"
        value: {{ readFile "./values/config.alloy" | b64enc }}
      
