repositories:
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: minio-operator
    url: https://operator.min.io
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  # S3 Storage 
  - name: minio-operator
    namespace: minio-operator
    chart: minio-operator/operator
    version: 6.0.1
    #values:
      #   - ./values/minio.values.yaml
  - name: minio-grafana
    namespace: minio
    chart: minio-operator/tenant
    version: 6.0.1
    values:
     - ./values/minio.values.yaml
  - name: loki
    namespace: grafana-stack
    chart: grafana/loki
    version: 6.7.3
    values:
      - ./values/loki.values.yaml
  - name: grafana
    namespace: grafana-stack
    chart: grafana/grafana
    version: 8.4.1
    values:
      - ./values/grafana.values.yaml
  - name: alloy
    namespace: grafana-stack
    chart: grafana/alloy
    values:
      - ./values/alloy.values.yaml
    set:
      - name: config.alloy
        file: ./values/config.alloy
  - name: tempo
    namespace: grafana-stack
    chart: grafana/tempo
    values:
      - ./values/tempo.values.yaml
  - name: pyroscope
    namespace: grafana-stack
    chart: grafana/pyroscope
    values:
      - ./values/pyroscope.values.yaml
  - name: prometheus
    namespace: grafana-stack
    chart: prometheus-community/prometheus
    values:
      - ./values/prometheus.values.yaml



      
